-- 1. LOAIHANG
CREATE TABLE LOAIHANG (
    MaLoaiHang VARCHAR(10) PRIMARY KEY,
    TenLoaiHang NVARCHAR(50) NOT NULL
);

-- 2. NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MaCT VARCHAR(10) PRIMARY KEY,
    TenCongTy NVARCHAR(100) NOT NULL,
    TenGiaoDich NVARCHAR(100),
    DiaChi NVARCHAR(150),
    DienThoai VARCHAR(20),
    Fax VARCHAR(20),
    Email VARCHAR(50)
);

-- 3. MATHANG
CREATE TABLE MATHANG (
    MaHang VARCHAR(10) PRIMARY KEY,
    TenHang NVARCHAR(100) NOT NULL,
    MaCT VARCHAR(10) REFERENCES NHACUNGCAP(MaCT),
    MaLoaiHang VARCHAR(10) REFERENCES LOAIHANG(MaLoaiHang),
    SoLuong INT,
    DonViTinh NVARCHAR(20),
    GiaHang DECIMAL(18,2)
);

-- 4. KHACHHANG
CREATE TABLE KHACHHANG (
    MaKH VARCHAR(10) PRIMARY KEY,
    TenCongTy NVARCHAR(100) NOT NULL,
    TenGiaoDich NVARCHAR(100),
    DiaChi NVARCHAR(150),
    Email VARCHAR(50),
    DienThoai VARCHAR(20),
    Fax VARCHAR(20)
);

-- 5. NHANVIEN
CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    Ho NVARCHAR(20),
    Ten NVARCHAR(20) NOT NULL,
    NgaySinh DATE,
    NgayLamViec DATE,
    DiaChi NVARCHAR(150),
    DienThoai VARCHAR(20),
    LuongCoBan DECIMAL(18,2),
    PhuCap DECIMAL(18,2)
);

-- 6. DONDATHANG
CREATE TABLE DONDATHANG (
    SoHD VARCHAR(10) PRIMARY KEY,
    MaKH VARCHAR(10) REFERENCES KHACHHANG(MaKH),
    MaNV VARCHAR(10) REFERENCES NHANVIEN(MaNV),
    NgayDatHang DATE,
    NgayChuyenHang DATE,
    NoiGiaoHang NVARCHAR(150)
);

-- 7. CHITIETDATHANG
CREATE TABLE CHITIETDATHANG (
    SoHD VARCHAR(10) REFERENCES DONDATHANG(SoHD),
    MaHang VARCHAR(10) REFERENCES MATHANG(MaHang),
    GiaBan DECIMAL(18,2),
    SoLuong INT,
    MuaGiamGia DECIMAL(18,2),
    PRIMARY KEY (SoHD, MaHang)
);

-- DUMMY DATA --
INSERT INTO LOAIHANG VALUES ('LH01', N'Điện tử'), ('LH02', N'Gia dụng');
INSERT INTO NHACUNGCAP VALUES ('NCC01', N'SamSung VN', 'SAMSUNG', N'Hà Nội', '0123', '0124', 'ss@mail.com');
INSERT INTO MATHANG VALUES ('MH01', N'Galaxy S26', 'NCC01', 'LH01', 50, N'Chiếc', 20000000);
INSERT INTO KHACHHANG VALUES ('KH01', N'Công ty Toàn Cầu', 'GLOBAL', N'Đà Nẵng', 'gb@mail.com', '0905', '0906');
INSERT INTO NHANVIEN VALUES ('NV01', N'Nguyễn Văn', N'An', '1995-01-01', '2020-01-01', N'Hà Nội', '0912', 10000000, 1000000);
INSERT INTO DONDATHANG VALUES ('HD01', 'KH01', 'NV01', '2026-06-01', '2026-06-03', N'Đà Nẵng');
INSERT INTO CHITIETDATHANG VALUES ('HD01', 'MH01', 19500000, 2, 500000);

SELECT  Ho,Ten, (LuongCoBan + IFNULL(PhuCap, 0)) AS TongLuong
FROM NHANVIEN;

SELECT KH.TenCongTy, NoiGiaoHang, KH.DiaChi
FROM DONDATHANG DDH, inner join KHACHHANG KH
ON DDH.MaKH = KH.MaKH, NHACUNGCAP NCC
WHERE NCC.DiaChi = NoiGiaoHang;

SELECT MaHang,TenHang, TenCongTy
FROM MATHANG MH, NHACUNGCAP NCC
WHERE NCC.MaCT = MH.MaCT;

SELECT MaHang, TenHang
FROM MATHANG
WHERE GiaHang > 100000 AND SoLuong < 50;

SELECT B.Ho, B.Ten, B.NgaySinh
FROM NHANVIEN A, NHANVIEN B
WHERE A.NgaySinh = B.NgaySinh and A.MaNV <> B.MaNV